//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeckleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTopic
    {
        public Nullable<int> Art { get; set; }
        public Nullable<int> To_Do_List { get; set; }
        public Nullable<int> Recipes { get; set; }
        public Nullable<int> Makeup { get; set; }
        public Nullable<int> Hair_Care { get; set; }
        public Nullable<int> Travel { get; set; }
        public Nullable<int> Men_s_Lifestyle { get; set; }
        public Nullable<int> Skin_Care { get; set; }
        public Nullable<int> Healthy__Eating { get; set; }
        public Nullable<int> Sports { get; set; }
        public Nullable<int> History { get; set; }
        public Nullable<int> Lifestyle { get; set; }
        public Nullable<int> Fitness { get; set; }
        public Nullable<int> Finance { get; set; }
        public Nullable<int> Fashion { get; set; }
        public Nullable<int> Recipies { get; set; }
        public Nullable<int> Suicide_Prevnetion { get; set; }
        public int BlogID { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
