//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeckleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ChatID { get; set; }
        public string ContactID { get; set; }
        public string Message1 { get; set; }
        public Nullable<System.DateTime> DateandTimeofMessage { get; set; }
        public Nullable<int> ProfileID { get; set; }
    
        public virtual ProfileDetail ProfileDetail { get; set; }
    }
}
